name: Init

on:
  workflow_call:

jobs:
  init_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Cache dev-py environment
        uses: actions/cache@v3
        with:
          path: .venv_ipyvizzu_story
          key: dev-py-${{ hashFiles('dev-requirements.txt') }}

      - name: Init dev-py environment
        run: |
          make check-dev-py
          make dev-py

      - name: Cache dev-js environment
        uses: actions/cache@v3
        with:
          path: node_modules
          key: dev-js-${{ hashFiles('package-lock.json') }}

      - name: Init dev-js environment
        run: |
          make check-dev-js
          make dev-js
